### PR TITLE
Adding git pre-commit hook

### PR DESCRIPTION
**Pull request by brianroch**
Fix for https://github.com/APIDevTools/swagger-cli/issues/26

Adding integration with git pre-commit hook.

### CODE REVIEW

**Comment by JamesMessinger** [comment]
At first I was very confused by this PR, because I was pretty certain that git hooks are shell scripts in the `.git/hooks` directory, **not** YAML files buried under the `node_modules` directory.  I even re-read the [Git Hooks documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)  just to make sure I wasn't crazy.

Only after a bit of googling did I discover that this `.pre-commit-hooks.yaml` file is actually for a Python tool called [pre-commit](https://pre-commit.com/), which I had never heard of before. 

So, now that I figured that out, a couple points:

**1. Thanks for introducing me to a new tool!**
I'll have to check it out sometime and maybe use it on some projects.

**2. More documentation is needed.**
Thank you for adding to the README file, but can you flesh it out a bit more to save other people from the confusion and googling that I did.  Link to the [pre-commit](https://pre-commit.com/) website and clarify what to do with the YAML snippet.

**Comment by brianroch** [comment]
Totally understand. I was elbow deep in working with this pre-commit tool, so my update was definitely lacking a bit of context. Happy to add that.

**Comment by brianroch** [comment]
@JamesMessinger Just wondering if there is an issue with Travis CI. The build was created three days ago and it's still in a queued state?

**Comment by JamesMessinger** [comment]
@brianroch - No worries.  Sometimes Travis gets out-of-sync with GitHub.   Your changes look good to me, so I'm gonna merge the PR.  Thanks a ton!

**Pull request merged**
